# -*- coding: utf-8 -*-
"""Boosting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQhW_5mxWofS6zR3IB-CaJAVsa7X7BcS
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/developer_burnout_dataset_7000.csv')
df

df.info()

df.isnull().sum()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['burnout_level']=le.fit_transform(df['burnout_level'])
df

from sklearn.impute import KNNImputer
knn=KNNImputer(n_neighbors=5)
df['burnout_level']=knn.fit_transform(df[['burnout_level']])

df.isnull().sum()

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
df['experience_years']=sc.fit_transform(df[['experience_years']])
df['age']=sc.fit_transform(df[['age']])
df['daily_work_hours']=sc.fit_transform(df[['daily_work_hours']])
df['sleep_hours']=sc.fit_transform(df[['sleep_hours']])
df['caffeine_intake']=sc.fit_transform(df[['caffeine_intake']])
df['bugs_per_day']=sc.fit_transform(df[['bugs_per_day']])
df['commits_per_day']=sc.fit_transform(df[['commits_per_day']])
df['meetings_per_day']=sc.fit_transform(df[['meetings_per_day']])
df['screen_time']=sc.fit_transform(df[['screen_time']])
df['exercise_hours']=sc.fit_transform(df[['exercise_hours']])
df['stress_level']=sc.fit_transform(df[['stress_level']])

df['experience_years']=knn.fit_transform(df[['experience_years']])
df['age']=knn.fit_transform(df[['age']])
df['daily_work_hours']=knn.fit_transform(df[['daily_work_hours']])
df['sleep_hours']=knn.fit_transform(df[['sleep_hours']])
df['caffeine_intake']=knn.fit_transform(df[['caffeine_intake']])
df['bugs_per_day']=knn.fit_transform(df[['bugs_per_day']])
df['commits_per_day']=knn.fit_transform(df[['commits_per_day']])
df['meetings_per_day']=knn.fit_transform(df[['meetings_per_day']])
df['screen_time']=knn.fit_transform(df[['screen_time']])
df['exercise_hours']=knn.fit_transform(df[['exercise_hours']])
df['stress_level']=knn.fit_transform(df[['stress_level']])

df.isnull().sum()

x=df.drop('burnout_level',axis=1)
y=df['burnout_level']

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score

model = AdaBoostClassifier(n_estimators=50, learning_rate=1)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("AdaBoost Accuracy:", accuracy_score(y_test, y_pred))

from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("Gradient Boosting Accuracy:", accuracy_score(y_test, y_pred))

from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    eval_metric='logloss'
)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("XGBoost Accuracy:", accuracy_score(y_test, y_pred))

from lightgbm import LGBMClassifier

model = LGBMClassifier(n_estimators=100, learning_rate=0.1)

model.fit(x_train, y_train)
y_pred = model.predict(x_test)

print("LightGBM Accuracy:", accuracy_score(y_test, y_pred))

!pip install catboost
from catboost import CatBoostClassifier

model = CatBoostClassifier(iterations=100, learning_rate=0.1, verbose=0)

model.fit(x_train, y_train)
y_pred = model.predict(x_test)

print("CatBoost Accuracy:", accuracy_score(y_test, y_pred))

from sklearn.ensemble import HistGradientBoostingClassifier

model = HistGradientBoostingClassifier(max_iter=100)

model.fit(x_train, y_train)
y_pred = model.predict(x_test)

print("HistGB Accuracy:", accuracy_score(y_test, y_pred))

from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    subsample=0.8
)

model.fit(x_train, y_train)
y_pred = model.predict(x_test)

print("Stochastic GB Accuracy:", accuracy_score(y_test, y_pred))

