# -*- coding: utf-8 -*-
"""Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wGr0Ez0PR7Wm4yh18Wln1dZfxJljMZbv
"""

import pandas as pd
import numpy as np
df=pd.read_csv("/content/gender_classification_v7.csv", encoding='latin1')
df

df.shape

df.columns

df.info()

df.isnull().sum()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['gender']=le.fit_transform(df['gender'])
df

x=df.drop(['gender'],axis=1)
y=df['gender']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.tree import DecisionTreeClassifier
dc=DecisionTreeClassifier()
dc.fit(x_train,y_train)

from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'criterion': ['gini', 'entropy', 'log_loss'],
    'splitter': ['best', 'random'],
    'max_depth': [None, 5, 10, 15, 20, 30, 50],

}
grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit = True, verbose = 5,n_jobs=-1,scoring='f1_weighted')

# fitting the model for grid search
grid.fit(x_train, y_train)

y_pred=dc.predict(x_test)
y_pred

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

