# -*- coding: utf-8 -*-
"""cross validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TAnOQgvDzbLIrY_zJwYWlhwBvSZhPBk4
"""

import pandas as pd

df=pd.read_csv('/content/loan_data.csv')

df

df.info()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in df.columns:
  if df[i].dtype=='object':
    df[i]=le.fit_transform(df[i])

from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
for i in df.columns:
  if df[i].dtypes == float :
    df[i]=ss.fit_transform(df[[i]])
df.head()

for i in df.columns:
  if df[i].dtype=='object':
    df[i]=le.fit_transform(df[i])

x=df.drop('loan_status',axis=1)
y=df['loan_status']

from sklearn.model_selection import KFold, cross_val_score

kfold = KFold(n_splits=5, shuffle=True, random_state=42)

from sklearn.naive_bayes import BernoulliNB
nb=BernoulliNB()

model=BernoulliNB()

scores = cross_val_score(nb, x, y, cv=kfold, scoring='accuracy')

scores

nb.fit(x,y)

from sklearn.metrics import accuracy_score
accuracy_score(y,nb.predict(x))

