# -*- coding: utf-8 -*-
"""CV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15wsrdKrvON5GBfNlS7hmNnFd0zlaPfLw
"""

import cv2

face_detector = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
)

img = cv2.imread("/content/30 Cats Who Decided To Pretend To Be Penguins.jpg")

from google.colab.patches import cv2_imshow
cv2_imshow(img)

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

gray

faces = face_detector.detectMultiScale(
    gray,
    scaleFactor=1.1,
    minNeighbors=5,
    minSize=(30, 30)
)

for (x, y, w, h) in faces:
    cv2.rectangle(
        img,
        (x, y),
        (x+w, y+h),
        (255, 0, 0),
        2
    )

cv2_imshow(img)
cv2.waitKey(0)
cv2.destroyAllWindows()