# -*- coding: utf-8 -*-
"""CV_VIDEO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_cWYR4pje4aNi5J0Auh3zydublMgYavt
"""

import cv2

from google.colab.patches import cv2_imshow

face_detector = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
)

video = cv2.VideoCapture("/content/143762-784138214_medium.mp4")

last_frame_with_faces = None
while True:
    ret, frame = video.read()
    if not ret:
        break
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_detector.detectMultiScale(
        gray,
        scaleFactor=1.1,
        minNeighbors=5,
        minSize=(30, 30)
    )
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)
    last_frame_with_faces = frame.copy()

if last_frame_with_faces is not None:
    cv2_imshow(last_frame_with_faces)
else:
    print("No frames were processed from the video.")

video.release()

import cv2

# Face detector
face_detector = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
)

# Read input video
video = cv2.VideoCapture("/content/VID_20260308_002910818.mp4")

# Video properties
width = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(video.get(cv2.CAP_PROP_FPS))

# Save output video
output = cv2.VideoWriter(
    "/content/output.mp4",
    cv2.VideoWriter_fourcc(*'mp4v'),
    fps,
    (width, height)
)

while True:

    ret, frame = video.read()

    if not ret:
        break

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    faces = face_detector.detectMultiScale(
        gray,
        scaleFactor=1.1,
        minNeighbors=5,
        minSize=(30, 30)
    )

    for (x, y, w, h) in faces:
        cv2.rectangle(
            frame,
            (x, y),
            (x+w, y+h),
            (255, 0, 0),
            2
        )

    output.write(frame)

video.release()
output.release()

print("Video processing completed!")

from google.colab import files
files.download("/content/output.mp4")