# -*- coding: utf-8 -*-
"""FNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gSynKyviXM3rU70g5_mF2MiUytQkcLRv
"""

import numpy as np
import pandas as pd

df=pd.read_csv("//content/loan_data.csv")

df

df.isnull().sum()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in df.columns:
  if df[i].dtype == object:
    df[i]=le.fit_transform(df[i])
df.head()

from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
for i in df.columns:
  if df[i].dtypes == float :
    df[i]=ss.fit_transform(df[[i]])
df.head()

x=df.drop(['loan_status'],axis=1)
y=df['loan_status']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=52)

import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(64, activation='relu', ),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.summary()

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

fnn = model.fit(x_train, y_train, epochs=300, batch_size=46)

y_pred=model.predict(x_test)
y_pred

