# -*- coding: utf-8 -*-
"""IQR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CXfz46PqW6tru26n-OVrFDx5ocNTQcAB
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/weather_classification_data.csv")

df.columns

df

df.isnull().sum()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
sns.boxplot(y=df['Temperature'])
plt.title('Box Plot of Temperature to Check for Outliers')
plt.ylabel('Temperature')
plt.show()

df['Temperature'] = pd.to_numeric(df['Temperature'], errors='coerce')

median_temperature = df['Temperature'].median()
df['Temperature'] = df['Temperature'].fillna(median_temperature)

# Calculate Q1, Q3, and IQR
Q1 = df['Temperature'].quantile(0.25)
Q3 = df['Temperature'].quantile(0.75)
IQR = Q3 - Q1

# Calculate lower and upper bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Apply capping
df['Temperature'] = np.where(df['Temperature'] < lower_bound, lower_bound, df['Temperature'])
df['Temperature'] = np.where(df['Temperature'] > upper_bound, upper_bound, df['Temperature'])

print(f"'Temperature' column capped between {lower_bound} and {upper_bound}.")

# Display basic statistics to show the effect
print("\nUpdated Temperature statistics after simple capping:")
print(df['Temperature'].describe())

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
sns.boxplot(y=df['Temperature'])
plt.title('Box Plot of Temperature to Check for Outliers')
plt.ylabel('Temperature')
plt.show()

