# -*- coding: utf-8 -*-
"""Kmean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYk6PejyF8wmrEblgYXNpS93pVbJ9qNO
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/gender_classification_v7.csv")

df

df.isnull().sum()

import seaborn as sns
import matplotlib.pyplot as plt

numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns

for column in numerical_cols:
    plt.figure(figsize=(8, 6))
    sns.boxplot(y=df[column])
    plt.title(f'Box Plot of {column} to Check for Outliers')
    plt.ylabel(column)
    plt.show()

numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns

for column in numerical_cols:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df[column] = np.where(df[column] < lower_bound, lower_bound, df[column])
    df[column] = np.where(df[column] > upper_bound, upper_bound, df[column])

    print(f"'{column}' column capped between {lower_bound:.2f} and {upper_bound:.2f}.")
    print(f"\nUpdated {column} statistics after simple capping:")
    print(df[column].describe())
    print("\n" + "-"*50 + "\n")

numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns

for column in numerical_cols:
    plt.figure(figsize=(8, 6))
    sns.boxplot(y=df[column])
    plt.title(f'Box Plot of {column} to Check for Outliers')
    plt.ylabel(column)
    plt.show()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['gender']=le.fit_transform(df['gender'])

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
df['forehead_width_cm']=sc.fit_transform(df[['forehead_width_cm']])
df['forehead_height_cm']=sc.fit_transform(df[['forehead_height_cm']])
df['nose_wide']=sc.fit_transform(df[['nose_wide']])
df['nose_long']=sc.fit_transform(df[['nose_long']])
df['lips_thin']=sc.fit_transform(df[['lips_thin']])
df['distance_nose_to_lip_long']=sc.fit_transform(df[['distance_nose_to_lip_long']])
df['long_hair']=sc.fit_transform(df[['long_hair']])

df

df.isnull().sum()

df.info()

df

x=df.drop('gender',axis=1)

from sklearn.cluster import KMeans

error = []
for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(x)
    error.append(kmeans.inertia_)

plt.figure(figsize=(10, 6))
plt.plot(range(1, 11), error, marker='o', linestyle='--')
plt.title('Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('ERROR (Inertia)')
plt.xticks(range(1, 11))
plt.grid(True)
plt.show()

kmeans = KMeans(n_clusters=2, random_state=42)
clusters = kmeans.fit(x)

clusters = kmeans.fit_predict(x)

clusters

df['Cluster'] = clusters

df['Cluster']

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(x)

plt.figure()
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=clusters)
plt.title("K-Means Clustering (PCA Visualization)")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.show()

from sklearn.metrics import silhouette_score
silhouette_avg = silhouette_score(x, clusters)
print("Silhouette Score:", silhouette_avg)

from sklearn.cluster import DBSCAN

dbscan = DBSCAN(eps=1.5,min_samples=5)
labels = dbscan.fit_predict(x)

labels

from sklearn.metrics import silhouette_score
silhouette_avg = silhouette_score(x, labels)
print("Silhouette Score:", silhouette_avg)

plt.figure()
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=labels, cmap='viridis')
plt.title("DBSCAN Clustering (PCA Visualization)")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.show()

from sklearn.ensemble import IsolationForest
iso=IsolationForest(
    n_estimators=100,
    contamination=0.02,
    random_state=42
)

iso.fit(x)

y_pred = iso.predict(x)


y_pred = np.where(y_pred == -1, 1, 0)

df['Anomaly'] = y_pred

df['Anomaly']

print("Total anomalies detected:", df['Anomaly'].sum())
print(df[df['Anomaly'] == 1].tail())

plt.figure(figsize=(8,6))
plt.scatter(x.iloc[:, 0], x.iloc[:, 1], c=y_pred)
plt.title("Isolation Forest - Anomaly Detection")
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.show()

