# -*- coding: utf-8 -*-
"""knn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sveQ2-hgRY-jLAL0AfqgIXn9t2tWqzvx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/fake_bills.csv', delimiter=';')

df

df.info()

df['margin_low'] = df['margin_low'].fillna(df['margin_low'].mean())
df.isnull().sum()

x=df.drop(['is_genuine'],axis=1)
y=df['is_genuine']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=52)

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()

from sklearn.metrics import accuracy_score

accuracies = []

for k in range(1, 21):
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(x_train, y_train)
    y_pred_k = model.predict(x_test)
    acc = accuracy_score(y_test, y_pred_k)
    accuracies.append(acc)

plt.plot(range(1, 21), accuracies, marker='o')
plt.xlabel("K value")
plt.ylabel("Accuracy")
plt.title("Choosing Optimal K")
plt.show()

knn=KNeighborsClassifier(n_neighbors=3)

knn.fit(x_train,y_train)

from sklearn.model_selection import GridSearchCV
# Define the parameter grid
param_grid = {
    'n_neighbors': [3,2,5],
    'weights': ['uniform', 'distance'],
    'p': [1, 2]
}
#grid
grid_search = GridSearchCV(knn, param_grid, cv=5)
grid_search.fit(x_train, y_train)

y_pred=knn.predict(x_test)
y_pred

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

