# -*- coding: utf-8 -*-
"""Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDhpNyeJb7aArGKWLPEGjRbiZ8EX9t1I
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/House Price Prediction Dataset.csv')
df

df.shape

df.head()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Location']=le.fit_transform(df['Location'])
df['Condition']=le.fit_transform(df['Condition'])
df['Garage']=le.fit_transform(df['Garage'])
df

df.isnull().sum()

x=df[['Bathrooms','Bedrooms','Floors','Area','Condition']]
y=df['Price']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=56)

from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
y_pred

from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

