# -*- coding: utf-8 -*-
"""Regressor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-aatdupuOo9-ZYYJsLAsDkDcxagTFLFQ
"""

import pandas as pd
import numpy as np
df=pd.read_csv("/content/car_price_prediction.csv", encoding='latin1')
df

df.shape

df.columns

df.info()

df.isnull().sum()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Levy']=le.fit_transform(df['Levy'])
df['Manufacturer']= le.fit_transform(df['Manufacturer'])
df['Model']= le.fit_transform(df['Model'])
df['Category']= le.fit_transform(df['Category'])
df['Leather interior']= le.fit_transform(df['Leather interior'])
df['Fuel type']= le.fit_transform(df['Fuel type'])
df['Engine volume']= le.fit_transform(df['Engine volume'])
df['Gear box type']= le.fit_transform(df['Gear box type'])
df['Drive wheels']= le.fit_transform(df['Drive wheels'])
df['Doors']= le.fit_transform(df['Doors'])
df['Wheel']= le.fit_transform(df['Wheel'])
df['Color']= le.fit_transform(df['Color'])
df['Mileage']= le.fit_transform(df['Mileage'])
df

df.info()

x=df.drop(['Price'],axis=1)
y=df['Price']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.tree import DecisionTreeRegressor
dc=DecisionTreeRegressor()
dc.fit(x_train,y_train)

y_pred=dc.predict(x_test)
y_pred

from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

