# -*- coding: utf-8 -*-
"""RFE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JH22zZ6XUAfAZqSdEuUxuG3Vug2WFk3t
"""

import numpy as np
import pandas as pd
df=pd.read_csv("/content/bank_transactions_data_2.csv")
df

df.info()

df.isnull().sum()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["TransactionType"]=le.fit_transform(df["TransactionType"])
df['AccountID']=le.fit_transform(df['AccountID'])
df['TransactionID']=le.fit_transform(df['TransactionID'])
df['TransactionDate']=le.fit_transform(df['TransactionDate'])
df['Location']=le.fit_transform(df['Location'])
df['MerchantID']=le.fit_transform(df['MerchantID'])
df['DeviceID']=le.fit_transform(df['DeviceID'])
df['IP Address']=le.fit_transform(df['IP Address'])
df['Channel']=le.fit_transform(df['Channel'])
df['CustomerOccupation']=le.fit_transform(df['CustomerOccupation'])
df['PreviousTransactionDate']=le.fit_transform(df['PreviousTransactionDate'])
df

from sklearn.model_selection import train_test_split

y = df["TransactionType"]
X = df.drop("TransactionType", axis=1)

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
rfe = RFE(model,n_features_to_select=5)
rfe.fit(X_train, y_train)

print(rfe.support_)
print(rfe.ranking_)
y_pred=rfe.predict(X_test)
y_pred

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,r2_score
accuracy_score(y_test,y_pred)

selected_features = X_train.columns[rfe.support_]
print("Top 10 features selected for training:")
for feature in selected_features:
    print(feature)

