# -*- coding: utf-8 -*-
"""RNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RPJJuAVs2U1EAoFxksSbudqMcJjwGcPW
"""

import pandas as pd
import numpy as np
import tensorflow as tf

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('spam.csv', encoding='latin-1')

df.head()

df = df[['v1', 'v2']]

df.columns = ['label', 'message']

df.head()

encoder = LabelEncoder()

df['label'] = encoder.fit_transform(df['label'])

X = df['message']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

tokenizer = Tokenizer(num_words=5000)

tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

max_len = 100

X_train_pad = pad_sequences(X_train_seq, maxlen=max_len)
X_test_pad = pad_sequences(X_test_seq, maxlen=max_len)

model = tf.keras.Sequential([

    tf.keras.layers.Embedding(
        input_dim=5000,
        output_dim=64,
        input_length=max_len
    ),

    tf.keras.layers.SimpleRNN(64),

    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

history = model.fit(
    X_train_pad,
    y_train,
    epochs=5,
    validation_data=(X_test_pad, y_test)
)

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend()
plt.show()

loss, accuracy = model.evaluate(X_test_pad, y_test)

print("Accuracy:", accuracy)

text = ["Congratulations! You won ₹10000"]

seq = tokenizer.texts_to_sequences(text)

pad = pad_sequences(seq, maxlen=max_len)

prediction = model.predict(pad)

print(prediction)

word_index = tokenizer.word_index

# Create a reverse word index for decoding (optional, but useful for understanding)
reverse_word_index = dict([(value, key) for (key, value) in word_index.items()])

# Adjust word index to account for special tokens (padding, start, unknown)
def preprocess_text(text):
    words = text.lower().split()
    encoded_review = []
    for word in words:
        # Get word index, default to 1 (unknown word token) if not found
        # Using 0 for padding as per Keras Tokenizer output, and 1 for unknown for consistency.
        encoded_review.append(word_index.get(word, 1))
    return encoded_review

def predict_review(text):
    # Preprocess the input text
    encoded_input = preprocess_text(text)
    # Pad the sequence to the model's expected input length
    padded_input = pad_sequences([encoded_input], maxlen=max_len)

    # Make a prediction
    prediction = model.predict(padded_input)
    return prediction[0][0]

# Example usage for spam classification:
user_message_spam = "Congratulations! You've won a free iPhone. Claim now!"
user_message_ham = "Hey, let's catch up later today."

print(f"Prediction for spam message: {predict_review(user_message_spam):.4f} (1 = spam, 0 = ham)")
print(f"Prediction for ham message: {predict_review(user_message_ham):.4f} (1 = spam, 0 = ham)")

user_text = input("Enter a message: ")

# Convert user text into sequence
sequence = tokenizer.texts_to_sequences([user_text])

# Padding
padded = pad_sequences(sequence, maxlen=max_len)

# Prediction
prediction = model.predict(padded)

# Output
if prediction[0][0] > 0.5:
    print("Spam Message")
else:
    print("Ham Message")

