# -*- coding: utf-8 -*-
"""Smote

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15PC007imqVUC9t9dsflw04xxMoaDkjeH
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/gender_classification_v7.csv')

df

df.columns

df.isnull().sum()

df.info()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
sns.boxplot(y=df['forehead_width_cm'])
plt.title('Box Plot of Forehead Width to Check for Outliers')
plt.ylabel('Forehead Width (cm)')
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(y=df['long_hair'])
plt.title('Box Plot of Long Hair to Check for Outliers')
plt.ylabel('Long Hair (0=No, 1=Yes)')
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(y=df['nose_wide'])
plt.title('Box Plot of Nose Wide to Check for Outliers')
plt.ylabel('Nose Wide (0=No, 1=Yes)')
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(y=df['lips_thin'])
plt.title('Box Plot of Lips Thin to Check for Outliers')
plt.ylabel('Lips Thin (0=No, 1=Yes)')
plt.show()

# Calculate Q1, Q3, and IQR
Q1 = df['long_hair'].quantile(0.25)
Q3 = df['long_hair'].quantile(0.75)
IQR = Q3 - Q1

# Calculate lower and upper bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Apply capping
df['long_hair'] = np.where(df['long_hair'] < lower_bound, lower_bound, df['long_hair'])
df['long_hair'] = np.where(df['long_hair'] > upper_bound, upper_bound, df['long_hair'])

print(f"'long_hair' column capped between {lower_bound} and {upper_bound}.")

# Display basic statistics to show the effect
print("\nUpdated long_hair statistics after simple capping:")
print(df['long_hair'].describe())



from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

df['gender']=le.fit_transform(df['gender'])

df

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

for i in df.columns:
  if df[i].dtype == 'float':
    df[i]=sc.fit_transform(df[[i]])

df

df.isnull().sum()

df['gender'].value_counts()

x=df.drop(['gender'],axis=1)

y=df['gender']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from imblearn.over_sampling import SMOTE

sm=SMOTE()

x_train,y_train=sm.fit_resample(x_train,y_train)

y_train.value_counts()

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

lr.fit(x_train,y_train)

y_pred=lr.predict(x_test)

y_pred

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

rf.fit(x_train,y_train)

y1_pred=rf.predict(x_test)

print(classification_report(y_test,y1_pred))